---
title: "SUMMA+ Dataset 1"
output: html_notebook
---

# Implement/test SUMMA+ library on Data Set 1 (Sonar)

## Preparations

```{r}
source('r_summa.R')
```

```{r}
#set.seed(1024)
data(Sonar)
inTraining0 <- createDataPartition(Sonar$Class, p = .75, list = FALSE)
training <- Sonar[ inTraining0,]
testing  <- Sonar[-inTraining0,]
testingY <- Sonar[-inTraining0, ncol(Sonar)]
```

```{r}
s1 <- summa(c('nnet', 'rda', 'pls', 'C5.0', 'ctree', 'knn', 'earth', 'avNNet', 'rpart'))
```

```{r}
s1 <- train(s1, Class~., training, update=F)
```

```{r}
s1 <- addmodel.summa(s1, c('C5.0', 'gbm'))
s1 <- train(s1, Class~., training, update=F)
```

```{r}
plot(s1)
```

```{r}
s1 <- predict(s1, testing, alpha=6, Y=testingY)
```

```{r}
s2 <- predict(s1, testing, newmodellist = c('nnet', 'pls', 'ctree', 'knn', 'earth', 'avNNet'), alpha=11, Y=testingY)
```

```{r}
print(s1)
```

```{r}
s1$testproblist$svmRadial[[1]]
```

```{r}
rocrank(s1$testproblist$svmRadial, testingY)
```

```{r}
res <- cal_score(s1, view=T)
```

```{r}
s1$modellist
```

